### PR TITLE
Add: Database Connection Manager with Doctrine DBAL

### PR DESCRIPTION
**Pull request by maznick**

### CODE REVIEW

**Comment by tavantzo** [comment]
@maznick Hi Niko,

thanks a lot for submitting your code.
Now what we are going to do is a QnA session using this PR so please don't use `commit --amend` or  `push -f` because the comments might be lost.

If changes will be request then just push them regularly with a new commit.

**Comment by maznick** [comment]
All the files are in models folder and the tests in tests folder. Please ignore index.php. I don't have anything in there and I should have removed it.
We should change the classes in order to be compatible with pdo or Eloquent if we want to switch to pdo or Eloquent.

**Comment by tavantzo** [comment]
@maznick Well, we don't have to be compatible with Eloquent or PDO we just need to create an **DB Abstraction Layer** according to what our system needs. So, using this **DBAL** we will be able to create **Adapters** to integrate either PDO, Eloquent, Doctrine or whichever 3rd party library we might want in our system.
Could you please update your PR according to that direction?

**Comment by maznick** [comment]
Hi George,
I am sorry for my late reply. I would need some more time to complete it. 
I would like to ask you if I don't use pdo I should work on the first layer of DBAL and only write the string queries. I can't imagine how this would be manual tested without any of the PHP libraries.

**Comment by tavantzo** [comment]
@maznick Hi Niko, 
I'm ok with taking more time.  Please, provide an estimate of how much time you will need. 

Regarding the tests, I believe you can create a simple dummy(ies) for your DBAL just to test the Db Connection manager behaviour since this might be the only concrete implementation in your solution.
Does this make it more clear to you?
Please let me know if there is anything else that I can help you.

**Comment by maznick** [comment]
Hi George,
I am still don't fully understand how will I execute the queries without using any library. 
I believe that until tomorrow night maximum on Wednesday I will send it back to you.
Will that be ok?

**Comment by tavantzo** [comment]
@maznick If you believe that you have to execute queries in order to test this then do as you please It won't be count as a mistake.

**Comment by tavantzo** [comment]
@maznick Thanks a lot,

the HR will contact you soon.

Best Regards

**Pull request closed without merging**
