### PR TITLE
Connection Manager

### PR DESCRIPTION
**Pull request by Navisot**

### CODE REVIEW

**Comment by tavantzo** [comment]
@Navisot Hi Niko,

thanks a lot for submitting your code.
Now what we are going to do is a QnA session using this PR so please don't use commit --amend or push -f because the comments might be lost, unless we request it

If changes will be request then just push them regularly with a new commit.

**Comment by Navisot** [comment]
Hi George,

I just removed the vendor folder.
Plz confirm.

Thanks

**Comment by tavantzo** [comment]
@Navisot Great, thanks. 

I'll get back you once I've finished the review.

**Comment by Navisot** [comment]
@tavantzo 
Comments are only available in methods. I didn't use comments on logic but i can add them if you want. For the syntax, it's not following exactly a code-style standard but it is close to PSR-1. Both comments and code-style didn't report on the project description so i did not pay much attention. Tests are available for validating PDO connection and CRUD. In project description you ask for an implementation of  a "database connection manager using an abstraction layer that could be implemented by any RDBMS". Maybe i am wrong but what i did is the implementation of an abstract layer that gives the opportunity to any RDBMS to successfully connect via my ConnectionManager and use my CRUD Model. Maybe you meant something else? Thanks!

**Comment by tavantzo** [comment]
@Navisot  
**About Coding Style**: Coding style isn't always dictated, but I as a coder, I tend to follow standards no matter what. In your code, you have a mixed code-style with PSR-1 and something else. But I guess this is a minor issue.

**About the BDAL:** Well, we need to create an **DB Abstraction Layer** according to what our system needs. So, using this **DBAL** we will be able to create **Adapters** to integrate either PDO, Eloquent, Doctrine or whichever 3rd party library we might want in our system.

Could you please update your PR according to that direction?

**Comment by Navisot** [comment]
@tavantzo 

Ok, i think i understand..but how about time? I mean, during the weekdays is hard for me to found time as i work. Can you give me some period estimation to work on project?
Thanks

**Comment by tavantzo** [comment]
@Navisot Based on your schedule, when do you believe that this would be ready? For us, there isn't a hard deadline but the sooner the better.

**Comment by Navisot** [comment]
For sure, i can't spend time until Wednesday because of a job deadline. So, i guess i can spend time on Thursday evening in order to commit again on Friday.
Is it ok?

Thanks

**Comment by tavantzo** [comment]
@Navisot That wouldn't be ok.

**Comment by Navisot** [comment]
@tavantzo 

I will try to have it ready tomorrow, but I'm not sure for the result.
I'll do my best.

Thanks

**Comment by Navisot** [comment]
Hi @tavantzo ,

Unfortunately, there is no time for me to make any update. As I said yesterday, I have deadline until Wednesday so its hard to spend time to another project. If you wish, you can send me another assignment for the weekend as i know the description of this assignment - not so fair.
Thanks

**Comment by tavantzo** [comment]
@Navisot Ok, I understand, Don't write any code but please just describe to me what you would have done in case you had the time?
Looking forward to your answer.

Best regards

**Comment by Navisot** [comment]
@tavantzo 
ok.
First of all, thanks for understand.

Now what i thought is below:

First I would make an interface connectionInterface with 2 methods: connect and getConnectionInstance. Then I would have a DatabaseManager class that implements the above interface. Then I would have a ModelCRUD class that would have an $orm protected variable which keeps the orm we wanna use, and two methods, one method for call DatabaseManager to get the connectionInstance and the other method*** would be responsible to associate $orm with db conection as it would take both $orm variable and $connection variable as parameters. Now,  maybe should exists another class called QueryObject that initializes an ORM class that extends ModelCRUD. The QueryObject should have a method ex. setORM(eloquent,etc..) in which as I said, will initialize ORM class and call a method selectORM(eloquent,etc..) that give us back the ormInstance. In the selectORM method (under ORM class) we set up the $orm variable as ORM extends the ModelCRUD and we call another function that connects orm with db connection. This method (mentioned above with asterisks) would be available in ModelCRUD class and help us to do the above jobs. (call DatabaseManager to get the db connection and the other method would be responsible to associate $orm with db connection, also will initialize the new orm in order to return it and have the methods of driver that somebody fill in the setORM method)

client:
$init = new QueryObject();
$model = $init->setORM('ELOQUENT');
$model->find(blabla);

**Comment by tavantzo** [comment]
Ok Niko,

thank you for your time. I guess that would be it with this phase. 
So, I guess the HR will contact you soon.

Best regards

**Pull request closed without merging**
