### PR TITLE
Front-end candidate test Bonus included

### PR DESCRIPTION
**Pull request by ChrikB**
xritos_dimitropoulos: frontend candidate test. 
Bonus included

### CODE REVIEW

**Comment by aris-b** [comment]
Thank you Xristo, we'll take a look and let you know.

**Comment by ChrikB** [comment]
Thank you Ari

________________________________
Από: Aris <notifications@github.com>
Στάλθηκε: Τρίτη, 3 Ιουλίου 2018 12:05 μμ
Προς: PeoplePerHour/candidate-tests
Κοιν.: Chris_b; Author
Θέμα: Re: [PeoplePerHour/candidate-tests] Front-end candidate test Bonus included (#16)


Thank you Xristo, we'll take a look and let you know.

**Comment by aris-b** [comment]
Hi @ChrikB, Thank you for your effort on working on the project and submitting this entry. I have carefully reviewed your project and code, and made the following notes:

- It works! So good job on this one. Also good job on using the libraries and tools I mentioned in the brief.
- The main issue is the code format. In order for someone to better understand code, it must be written with proper spacing, understandable variable names, and a in a bit more organized pieces.
That's why,  we mostly follow a styleguide (like the one at Airbnb I mentioned in the brief).
- The js modules (files) could have been organized by their purpose, this will help someone who dives in your code to better understand it and extend it if needed. Keeping it simple in most cases and being predictable is the key.
- You should not use tests in runtime of the application. 
- The SASS file is minimized, I cannot read it

**Comment by ChrikB** [comment]
Hello @aris-b

I did a second commit based on your notes.

New stuff is within  'pph-send-FRONTEND-2-xritos'
Since I went the ' serverless way' ,  I removed totally chai assertion tests from runtime as you mentioned.

If we continue further with the rest of interview stages and unit tests is the only missing part, then I will create this test from start using the node.js  and jest,enzyme etc for testing.

Thank you for your time to review the code.

**Pull request closed without merging**
