### PR TITLE
IoannaVrettou Front End task

### PR DESCRIPTION
**Pull request by IoannaVrettou**

### CODE REVIEW

**Comment by koox00** [comment]
@IoannaVrettou hallo, thx for submitting the test! can you exclude the `/node_modules` folder from version control?

**Comment by IoannaVrettou** [comment]
Hello Kyriakos,

I 've just seen your email. Unfortunately i don't have access to laptop! I
will be able to submit the project again on Thursday morning! Is that ok
for you?

Kindly,
Ioanna Vrettou

Στις Δευ, 31 Αυγ 2020, 5:14 μ.μ. ο χρήστης Kyriakos Z. <
notifications@github.com> έγραψε:

**Comment by IoannaVrettou** [comment]
Hello Kyriakos, 

i 've just pushed the changes you 've requested! Please review and contact me if it's necessary to do anything else!

**Comment by IoannaVrettou** [comment]
Hello Kyriakos,

i 've just pushed the changes you 've requested! Please review and contact
me if it's necessary to do anything else!


Kindly,

Ioanna Vrettou

Στις Τρί, 1 Σεπ 2020 στις 5:56 μ.μ., ο/η Ioanna Vrettou <iovrettou@gmail.com>
έγραψε:

**Pull request closed without merging**
